apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: walkguardianai-minio

resources:
  - resources/namespace.yaml
  - resources/pvc.yaml
  - resources/secret.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/route-api.yaml
  - resources/route-ui.yaml
